# Generated by Django 4.1.7 on 2023-03-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goalcategory_board'),
        ('bot', '0002_alter_tguser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goalcategory'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
